#!/bin/bash
rm -rf Build.*
date > "Build."`date +%y%m%d.%H%M`

BUILD_TAG=`ls Build*`
MESSAGE="Pushing CI/CD DARP Build $BUILD_TAG"
git add . && git commit -m "$MESSAGE" && git pull && git push 

git push origin :latest

git tag -f latest
git tag $BUILD_TAG
git push origin --tags

echo `date`" Completed git push for latest and $BUILD_TAG "
