#!/bin/bash
MESSAGE="Developing CI/CD DARP docker"
BUILD_TAG=`ls Build*`
git add . && git commit -m "$MESSAGE" && git pull && git push 

git push origin :latest

git tag -f latest
git tag $BUILD_TAG
git push origin --tags

echo `date`" Completed git push for latest and $BUILD_TAG "
