[package]
name = "rust_tinkering"
version = "0.1.0"
authors = ["William B. Norton <wbn@drpeering.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
